### ISSUE TITLE
Example in readme doesn't work

### ISSUE THREAD

**Issue by OmgImAlexis** [sashafklein/shape#2]
The example from the readme doesn't seem to be working.

```js
root@Devon:/mnt/disks/code/api# node -r esm
> import Shape, { string } from 'matches-shape';
undefined
>
> const shape = Shape.new({
...     values: [{ type: string }]
... });
TypeError: Shape.new is not a function
    at repl:1
    at Script.runInThisContext (vm.js:96:20)
    at REPLServer.defaultEval (repl.js:329:29)
    at bound (domain.js:396:14)
    at REPLServer.runBound [as eval] (domain.js:409:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:187:15)
```

**Comment by sashafklein** [comment]
Thanks! Typo, I think based on confusing JS/Ruby class initialization. Will fix presently.
